nmigen/back/pysim.py

At present the `root_fragment` in the pysim `hierarchy` has an empty `scope=()`, and when this is added to the vcd file we get:
```vcd
$scope module  $end
```
i.e. the top-level module has no name. This breaks gtkwave somewhat as you can't re-select the top level after selecting a submodule:
This patch sets the `root_fragment`'s scope to `"top"`, producing a vcd with a useful hierarchy:
I can't see an obvious way to get a more useful name than "top" for the root fragment, but if one exists that would be even better.

Give the top level scope a name to fix vcd file production

---

nmigen/__init__.py
nmigen/back/pysim.py
nmigen/back/rtlil.py
nmigen/hdl/ast.py
nmigen/hdl/xfrm.py

`AnyConst` and `AnySeq` correspond to to the `$anyconst` and `$anyseq` RTLIL cells. They are useful for formal verification to represent "any value that doesn't change", and "any value that _can_ change to another arbitrary value each clock cycle" respectively.
Usage is analogous to declaring a `Constant` or `Signal`:
```
self.foo = AnyConst(2)
self.bar = AnySeq(16)
```

Support for yosys' $anyconst and $anyseq cells

---

nmigen/cli.py

There should probably be a default for generate (as there is is hint already). This adds `v` as default for `-t`.

cli: add missing default for `generate`

---

setup.py

Installation should be constraint to supported Python versions, using `python_requires`, refer to [1] for details.
[1] https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

setup.py: constrain Python version

---

examples/por.py

`ResetSignal().eq(delay == 0)` should spell `ResetSignal().eq(delay != 0)` as `delay` counts down to zero.

examples.por: fix typo

---

nmigen/hdl/rec.py
nmigen/test/test_hdl_rec.py

This PR changes the seperator for signal names in records from a single underscore to a double underscore. When creating a Record, the signals inside it are then named `recordname__fieldname`.
This gives one more useful information, when looking at the signal names of fields which themselves contain underscores. E.g. `record__some_field` is now unambiguous :)
It closes #48.

Change name seperator for siganls in records to double underscore

---

nmigen/compat/fhdl/specials.py

It appears there's a typo in ``Tristate``, introduced w/ 287a0531b325c752a94d12ce6169a1de66c9569a .

compat.fhdl.specials: fix Tristate.

---

nmigen/vendor/lattice_ice40.py
nmigen/vendor/xilinx_7series.py
nmigen/vendor/xilinx_spartan6.py

@jfng Can you please review this, and make sure I didn't break anything? The main part here is the commit that removes the inverter between the register (FDCE) and tristate input of the IOB. The rest is just misc cleanups that remove intermediate signals and ensure that if a pin doesn't have e.g. the `i` signal, there is no `i` signal returned from `_get_xdr_buffer`.

Clean up Xilinx platform code

---

nmigen/vendor/xilinx_7series.py

I'm not quite sure if this is correct in general but I expect *.xdc* constraint extra files to be applied. This patch filters `extra_files` for `.xdc` endings and applies them using `read_xdc`.

vendor.xilinx_7series: read extra .xdc files.

---

nmigen/build/dsl.py
nmigen/test/test_build_dsl.py

Just as `Resource.family` makes it easier to generate `Resources` with a fallback name, this PR makes it easier to support `Resources` in `nmigen_boards` that only differ in features and should have identical prefixes names, such as SPI flashes with different widths.

build.dsl: Add optional name_suffix to Resource.family.

---

nmigen/build/run.py

The Windows command line is a mess.
When trying to synthesize some `nmigen` code today, I ran into a `nextpnr` problem that caused the whole build to fail. The batch script correctly exited early, but `CalledProcessError` was never raised (meaning return code from `check_call` was `0`). Since I had `do_program=True`, `plat.build` continued, and this cascaded into more errors:
```
William@WILLIAM-THINK C:\msys64\home\William\src\icebreaker-nmigen-examples\pdm_fade_gamma
> python3 gamma_pdm.py
ERROR: Top-level input 'I0' also driven by I0.O.
ERROR: Loading design failed.
0 warnings, 2 errors
Traceback (most recent call last):
File "C:\msys64\home\william\src\nmigen\nmigen\build\run.py", line 120, in extract
file.write(self.get(filename))
File …
```

build.run: Ensure batch script returns proper error code.

---

nmigen/lib/fifo.py

*DomainsRenamer* should spell *DomainRenamer*.

lib.fifo: fix typo.

---

nmigen/hdl/dsl.py
nmigen/test/test_hdl_dsl.py

This allows retrieving a named submodule after assigning it:
```
>>> m1 = Module()
>>> m1.submodules.m2 = Module()
>>> m1.submodules.m2
<nmigen.hdl.dsl.Module object at 0x7f2acc2cf240>
```
It also disallows setting the same submodule name twice:
```
>>> m1 = Module()
>>> m1.submodules.m2 = Module()
>>> m1.submodules.m2 = Module()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/nengel/nmigen/nmigen/hdl/dsl.py", line 85, in __setattr__
self._builder._add_submodule(submodule, name)
File "/home/nengel/nmigen/nmigen/hdl/dsl.py", line 432, in _add_submodule
raise ValueError("Submodule named '{}' already exists".format(name))
ValueError: Submodule named 'm2' already exists
```
Item notation is also supported:
```
>>> m1 = Module()
>>> m1.submodules['m2'] = …
```

add getters to m.submodules

---

nmigen/vendor/lattice_ecp5.py
nmigen/vendor/lattice_ice40.py
nmigen/vendor/xilinx_7series.py
nmigen/vendor/xilinx_spartan_3_6.py

Fixes #157.
Vendor files create a lot of IObufs with duplicate names:
```for bit in range(len(port)):
m.submodules[pin.name] = Instance(...)
```
which is no longer allowed as of 698b005.
This appends a suffix for each bit:
```
for bit in range(len(p_port)):
m.submodules["{}_{}".format(pin.name, bit)] = Instance(...)
```

remove duplicate iobuf submodule names

---

nmigen/test/test_examples.py

`subprocess.check_call` iterates over its arguments to check for spaces and tabs, and on Windows, the pathlib-specific WindowsPath is not iterable.
Before this change, the all tests in `test_examples.py` would fail with an error like this:
```
William@William-THINK MINGW64 ~/src/nmigen
$ python3 -m unittest
..............................................................................................EEEEEEEEEEEEE.......................................................................................................................................................................................................................................................................................................................................................... …
```

test.test_examples: Convert pathlib-specific class to string.

---

nmigen/vendor/xilinx_7series.py

STARTUPE3 is for Ultrascale and it fails to build for 7 series with this in there

Xilinx 7 series STARTUPE3->STARTUPE2

---

nmigen/vendor/lattice_ecp5.py

This was missing.
I needed this for passing `--idcode 0x21111043` [ref](https://github.com/SymbiFlow/prjtrellis/issues/55) which is required for LFE5U-12F. Not sure if that should be automatically added if that part is selected.

pass ecppack_opts to ecppack

---

nmigen/vendor/xilinx_7series.py
nmigen/vendor/xilinx_spartan_3_6.py

Vivado was inferring an SRL16 from a MultiReg in some cases. This simply adds an `ASYNC_REG="TRUE"` attribute to the registers.
This code is identical for both 7 series and Spartan which I don't like. I see two possibilities: 
Add something like async_reg_attrs to the platform file and if present apply it to the regs in the MultiReg. It could also be applied to ResetSynchronizer, etc.
A new file, vendor/xilinx_common.py containing code common to all supported Xilinx parts.
I'm happy to do either.

Xilinx specific MultiReg

---

nmigen/vendor/altera.py

This adds SDR support for Altera chips, or at least enough flops and buffers for it.

vendor.altera: use buffer primitives

---

nmigen/hdl/rec.py

This is to make it easier to support the `like()` class method in subclasses of Record. If in the subclass the second argument to `__init__()` is not name one currently has to take into account that the second argument can actually be the name if the first argument is of type `Layout`.

Record: force name to be given by name for `__init__()`

---

nmigen/vendor/xilinx_7series.py
nmigen/vendor/xilinx_spartan_3_6.py
nmigen/vendor/xilinx_ultrascale.py

vendor.xilinx_*: Set IOB attribute on cells instead of nets.

---

nmigen/vendor/intel.py

Quartus complains a lot while building Yosys-generated Verilog:
- it fails some subjective lints (warnings 10270, 10763, 10935) that don't affect the semantics (modulo Yosys bugs).
- Quartus doesn't recognise certain attributes like `src` (warning 10335) generated by nMigen.
- Quartus will use its internal IP library whenever you instantiate a megafunction, and warn about it not being within the settings file (warning 12125).
- Quartus complains whenever you set `NUM_PARALLEL_PROCESSORS` to something which isn't all cores (warning 18236).
- Quartus Lite will also complain about unimportant features only being available when you buy Quartus (warning 292013).
These can be silenced through the creation of a `.srf` file (which in this case suppresses all message text with a given ID in …

vendor.intel: silence meaningless warnings

---

nmigen/hdl/ast.py
nmigen/test/test_hdl_ast.py

To properly represent a negation of a signed X-bit quantity we may, in
general, need a signed (X+1)-bit signal — for example, negation of
3-bit -4 is 4, which is not representable in signed 3 bits.

hdl.ast: Fix width for unary minus operator on signed argument.

---

nmigen/build/run.py

Got `None` from  `Platform.execute_local(self, root="build", *, run_script=False)`. This commit fixes that.

build.run: fix indentation.

---

nmigen/hdl/ast.py
nmigen/test/test_hdl_ast.py

Signal: allow to use integral Enum for reset value.

---

nmigen/test/utils.py

When attempting to parallelize verification tasks from within the same file, the `sby` verification tasks may encounter an error due to an attempt to access the same directory simultaneously, arising from a name collision in the generated `spec_name`. Adding the option to specify `spec_name` within `assertFormal` allows the caller to manually resolve such issues, while maintaining full backwards compatibility with existing scripts.

Add option to specify spec_name
